export const NAVIGATION_TABS_ADD_ITEM = "NAVIGATION_TABS_ADD_ITEM";
export const NAVIGATION_TABS_REMOVE_ITEM = "NAVIGATION_TABS_REMOVE_ITEM";
export const NAVIGATION_TABS_SEARCH_ITEM = "NAVIGATION_TABS_SEARCH_ITEM";
